// This file is auto-generated by GameConstantsGenerator.

namespace Demo
{
    /// <summary>
    /// Convenience class for UNITY Tags.
    /// </summary>
    public static class Tags
    {
        // UNITY Builtin tags.
        public const string Untagged = "Untagged";
        public const string Respawn = "Respawn";
        public const string Finish = "Finish";
        public const string EditorOnly = "EditorOnly";
        public const string MainCamera = "MainCamera";
        public const string Player = "Player";
        public const string GameController = "GameController";
        // Project specific values.
    }

    /// <summary>
    /// Convenience class for UNITY Layers.
    /// </summary>
    /// <remarks>
    /// If using <c>LayerMask</c> in Editor compiler can not check 'used layers' by name
    /// but it is easier to select correct layer(s).
    /// </remarks>
    public static class Layers
    {
        // UNITY Builtin layers
        public const int Default = 0;
        public const int TransparentFX = 1;
        public const int IgnoreRaycast = 2;
        public const int Water = 4;
        public const int UI = 5;
        // Project specific values.

        // Bitmask of UNITY Builtin layers
        public const int TransparentFXMask = 1 << 1;
        public const int IgnoreRaycastMask = 1 << 2;
        public const int WaterMask = 1 << 4;
        public const int UIMask = 1 << 5;
        // Project specific values.
    }

    /// <summary>
    /// Convenience class for UNITY SortingLayers
    /// </summary>
    /// <remarks>
    /// Typically 'sorting layers' are not used at all in the code.
    /// </remarks>
    public static class SortingLayers
    {
        /// <summary>
        /// ID of sorting layer 'Default'.
        /// </summary>
        public const int Default = 0;
    }
}
